Litera = "a" | "b" | "c" | "d" | "e" | "f" | "g" | "h" | "i" | "j" | "k" | "l" | "m" | "n" | "o" | "p" | "q" | "r" | "s" | "t" | "u" | "v" | "w" | "x" | "y" | "z";
Cifra   = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9";
Spatiu = " " , {" "};
OptSpatiu = "" | Spatiu;
Valoare = Cifra | "?";
Instructiuni = "Input" | "Output";

Variabila = OptSpatiu Litera "=" Valoare OptSpatiu;
Lista = Variabila | Variabila "," Lista;
DefinitieVar = OptSpatiu "Var" Spatiu Lista;
Instructiune = OptSpatiu Instructiuni Spatiu Litera;
Expresie = OptSpatiu Litera OptSpatiu "+" OptSpatiu Litera;
Atribuire = OptSpatiu Litera "=" OptSpatiu Expresie OptSpatiu;
Sintaxa = Instructiune | DefinitieVar | Atribuire;
